### ISSUE TITLE
Question about yaml format

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/capture-lookups#2]
I am not familiar with yaml. The code appears to work. So, this is just a question to clear up my confusion.

I notice that [the format for our mappings](https://raw.githubusercontent.com/forikal-uk/capture-lookups/feature/cli-command/mapping.yml) is as follows:
```

WithBatch:
  url: "https://docs.google.com/spreadsheets/d/1jOfsClbTj15YUqE-X2Ai9cvyhP-GLvP8CGZPgD1TysI/edit#gid=0"
  startingFromRow: 2
  batchGet: true

WithoutBatch:
  url: "https://docs.google.com/spreadsheets/d/1jOfsClbTj15YUqE-X2Ai9cvyhP-GLvP8CGZPgD1TysI/edit#gid=0"
  startingFromRow: 2
  batchGet: false
```

However I note on the yaml web site it describes a format like this:
```

Mark McGwire: {hr: 65, avg: 0.278}
Sammy Sosa: {
    hr: 63,
    avg: 0.288
  }
```

See [Yaml Spec > Example 2.6. Mapping of Mappings](http://yaml.org/spec/1.2/spec.html#id2759963)

So, in our project, which structure are we using for our mappings and is it documented somewhere officially? If so, were? 

Thanks

**Comment by janklan** [comment]
I probably shouldn't have used the term `mapping` as it has no relation to the YAML's website "Mapping of Mappings". It's just a name different than `LookupTable`. 

As per the syntax, these two will get you the same result:

```yaml
WithBatch:
  url: "https://docs.google.com/spreadsheets/d/1jOfsClbTj15YUqE-X2Ai9cvyhP-GLvP8CGZPgD1TysI/edit#gid=0"
  startingFromRow: 2
  batchGet: true

WithoutBatch: {
    url: "https://docs.google.com/spreadsheets/d/1jOfsClbTj15YUqE-X2Ai9cvyhP-GLvP8CGZPgD1TysI/edit#gid=0",
    startingFromRow: 2,
    batchGet: false
  }
```

I think the first one (without curly braces) is just simpler, so I used that. Also all other Symfony files use just a plain indentation method in their yml files.
